### ISSUE TITLE
Error when trying to get zero-shot performance

### ISSUE THREAD

**Issue by Boxiao-Yunshi** [deeptibhegde/CLIP-goes-3D#11]
When trying to estimate the zero-shot performance using the following command:

`python eval.py --config cfgs/ShapeNet55_models/PointTransformerVPT.yaml --exp_name exxx --ckpts point_transformer_1k.pth  --slip_model slip_base_100ep.pt --zshot`

Got the error: 

```
Traceback (most recent call last):
  File "/content/drive/MyDrive/CG3D/CLIP-goes-3D-main/eval.py", line 387, in <module>
    main()
  File "/content/drive/MyDrive/CG3D/CLIP-goes-3D-main/eval.py", line 169, in main
    clip_model.visual.load_state_dict(clip_dict)
  File "/content/miniconda3/envs/cg3d/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for VisionTransformer:
        Unexpected key(s) in state_dict: "prompt_embeddings", "deep_prompt_embeddings". 
```

Tried with the weights `point_transformer_1k.pth`, `point_transformer_8k.pth` and `pointmlp_8k.pth`., always the same error. Likely that I did something wrong, but any help is highly appreciated!

**Comment by deeptibhegde** [comment]
This was an issue with a previous version of the modified timm package. I have now removed the need to download it from an external drive, the package is available directly in the repository. Please pull the latest changes and let me know if you still face the same issue.
