### ISSUE TITLE
Is there any way we can install the environment on other cuda versions (e.g., CUDA 12.2)?

### ISSUE THREAD

**Issue by chenxinli001** [deeptibhegde/CLIP-goes-3D#17]
Is there any way we can install the environment on other cuda versions (e.g., CUDA 12.2)?

**Comment by deeptibhegde** [comment]
The codebase has not been tested on CUDA 12.2, however, there should not be any conflicts. Please reach out if you face errors.

**Comment by chenxinli001** [comment]
I mean when I install these dependencies (fig1), it seems that I am required to only do installation with CUDA 12.2 (fig2). i don't know if there is another way to solve it without requiring installing CUDA 12.2?

![image](https://github.com/deeptibhegde/CLIP-goes-3D/assets/58136000/069d809a-ff00-49b3-9a7f-ab47d177e8aa)
![image](https://github.com/deeptibhegde/CLIP-goes-3D/assets/58136000/cdc1be0a-4672-4dcb-a204-c51218e5e63d)

**Comment by deeptibhegde** [comment]
This looks like your CUDA version is 12.2. You can try recompiling from scratch, removing all build files, and making sure the PyTorch install matches with your CUDA version.
