### ISSUE TITLE
ScanObjectNN/main_split_image

### ISSUE THREAD

**Issue by 22way** [deeptibhegde/CLIP-goes-3D#21]
![QQ20241125-161507](https://github.com/user-attachments/assets/32e4ac6c-dfe1-43b6-be1e-ebd4ce7fbb23)
Is the ScanObjectNN/main_split_image not available in the dataset ScanObjectNN? How did this come about, thank you, and look forward to your reply

**Comment by deeptibhegde** [comment]
That is a custom split that includes the rendered images of ScanObjectNN objects to test the 2D zero-shot performance. It was created for debug purposes and is not required for general evaluation of the model.
